packages:
  - apps/*
  - packages/*
  - tools/*
overrides:
  tldraw: 3.15.5
allowBuilds:
  core-js: true
  esbuild: true
ignoredBuiltDependencies:
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - prisma
